/*
 * Copyright (c) 2017 Alex.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Alex - initial API and implementation and/or initial documentation
 */
package BasicElements.AdvancedViews;

import BasicViews.MainWindowForm;
import luna.databaseManager.DatabaseManager;
import luna.databaseManager.Session;

/**
 *
 * @author Alex
 */
public class MostNotebooksOrdered extends javax.swing.JFrame {

    private Session session;

    /**
     * Creates new form MostNotebooksOrdered
     */
    public MostNotebooksOrdered() {
        initComponents();
    }

    MostNotebooksOrdered(Session session) {
        this.session = session;
        initComponents();
        textArea1.setEditable(false);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                
                    MainWindowForm mwf = new MainWindowForm(session);
                    mwf.setVisible(true);
                
            }
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();
        jRadioButtonPriority = new javax.swing.JRadioButton();
        jRadioButtonStatus = new javax.swing.JRadioButton();
        jRadioButtonQuantity = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButtonPriority);
        jRadioButtonPriority.setText("Ordenar por prioridad");

        buttonGroup1.add(jRadioButtonStatus);
        jRadioButtonStatus.setText("Ordenar por status");

        buttonGroup1.add(jRadioButtonQuantity);
        jRadioButtonQuantity.setText("Ordenar por cantidad");

        jButton1.setText("Revisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPriority)
                    .addComponent(jRadioButtonStatus)
                    .addComponent(jRadioButtonQuantity)
                    .addComponent(jButton1))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jRadioButtonPriority)
                .addGap(30, 30, 30)
                .addComponent(jRadioButtonStatus)
                .addGap(31, 31, 31)
                .addComponent(jRadioButtonQuantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonQuantity.isSelected()){
            getMostOrderedNotebooks();
        }
        if(jRadioButtonStatus.isSelected()){
            getNotebooksByStatus();
        }
        if(jRadioButtonPriority.isSelected()){
            getNotebooksByPriority();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void getMostOrderedNotebooks(){
        textArea1.setText("");
        String [] notebooks = DatabaseManager.getMostOrderedNotebooks();
        textArea1.append("Pedidos ordenados por cliente con mayor cantidad de cuadernos a menor\n"
                + "ID \t Nombre \t Status \t Prioridad \t Cantidad \n");
        for(int i = 0;i < notebooks.length; i++){
            textArea1.append(notebooks[i]+"\n");
        }
    }
    
    private void getNotebooksByPriority(){
        textArea1.setText("");
        String [] notebooks = DatabaseManager.getMostOrderedNotebooksWithPriority();
        textArea1.append("Pedidos ordenados por prioridad\n"
                + "ID \t Nombre \t Cantidad \t Status \t Prioridad\n");
        for(int i = 0; i < notebooks.length; i++){
            textArea1.append(notebooks[i]+"\n");
        }
    }
    
    private void getNotebooksByStatus(){
        textArea1.setText("");
        String [] notebooks = DatabaseManager.getMostOrderedNotebooksWithStatus();
        textArea1.append("Pedidos ordenados por status\n"
                + "ID \t Nombre \t Cantidad \t Prioridad \t Status\n");
        for(int i = 0; i < notebooks.length; i++){
            textArea1.append(notebooks[i]+"\n");
        }        
    }    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostNotebooksOrdered.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostNotebooksOrdered.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostNotebooksOrdered.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostNotebooksOrdered.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostNotebooksOrdered().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonPriority;
    private javax.swing.JRadioButton jRadioButtonQuantity;
    private javax.swing.JRadioButton jRadioButtonStatus;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
